/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ApiTest: typeof import('./src/components/ApiTest.vue')['default']
    AppContainter: typeof import('./src/components/Layout/AppContainter.vue')['default']
    BlankLayout: typeof import('./src/components/Layout/BlankLayout.vue')['default']
    ExclamationCircleOutlined: typeof import('@ant-design/icons-vue')['ExclamationCircleOutlined']
    Home: typeof import('./src/components/Home.vue')['default']
    ModalTheme: typeof import('./src/components/ModalTheme.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
